### ISSUE TITLE
Setting Pattern Notes or CVs count to 0 on existing pattern crashes VCV Rack

### ISSUE THREAD

**Issue by reinh** [gibbonjoyeux/VCV-Biset#11]
In an otherwise empty VCV patch on a freshly initialized Tracker module, if I set Pattern notes to 0 and click Update pattern, VCV Rack will crash. I have also been able to crash VCV Rack by setting pattern CVs to zero in some situations, but I haven't found a reproduction yet.

![image](https://github.com/gibbonjoyeux/VCV-Biset/assets/52/8ab11398-ae03-45a4-a599-5b9570214135)

**Comment by gibbonjoyeux** [comment]
Thank you very much for this report !
I will try to send a fix on the next batch to the library :)
