### ISSUE TITLE
Delete button inconsistency

### ISSUE THREAD

**Issue by ivxvm** [gibbonjoyeux/VCV-Biset#13]
First of all, as many have said, Biset Tracker seems to be a real game changer of a module! Great work! One minor annoyance I noticed is that in pattern mode delete button works in context of pattern and clears current step, but then when I go to the timeline mode, select pattern and press delete, the whole module is gone instead of just pattern! 😅 It makes it quite easy to lose all your unsaved progress after sitting in pattern mode for a while. Would be nice if delete button just deleted the selected pattern imo.

**Comment by gibbonjoyeux** [comment]
Thanks for your message and for the report :)
I'd like to work on ctrl-z events for the Tracker to prevent issue like this where you lost all your data by removing accidentally the Tracker. For the pattern instance removal, I'm pretty sure that it was how I made it first but changed it to prevent some issue but I can't remember what Haha. I will try to send a fix to this in the 2.0.8 update (the 2.0.7 fixing some crashes and other bugs has already been sent to VCV).
Thanks again :)

**Comment by gibbonjoyeux** [comment]
Delete shortcut for pattern instances has been added and will be available with the 2.0.8 update :)
