### ISSUE TITLE
Shift rows up / down hotkeys

### ISSUE THREAD

**Issue by ivxvm** [gibbonjoyeux/VCV-Biset#14]
Would be really nice to have this, because currently if you want to insert some space or new notes between notes, you have to reprogram the rest of the pattern. Shift rows down can be synonym for "insert empty row at cursor", shift rows up can be rephrased as something like "delete current row and move everything after it 1 row up".

**Comment by gibbonjoyeux** [comment]
Thanks again for the message :)
It would indeed be really useful and it should not be too difficult to do that, I will try to add it to the 2.0.8 update !

**Comment by gibbonjoyeux** [comment]
Done, will be available with the next update soon :)
