### ISSUE TITLE
Scroll X axis in timeline view?

### ISSUE THREAD

**Issue by FuneralDust** [gibbonjoyeux/VCV-Biset#15]
Currently the timeline view only shows about 20 bars. If I add patterns, they spill past the screen but I can't scroll across to see them. How does one move along the X axis in timeline view? I'm not seeing this in the manual or the walkthrough video

**Comment by gibbonjoyeux** [comment]
You can scroll on X axis by pressing SHIFT down while scrolling :)
I will add it to the Manual and I'd also like to add some helps via context menu (right click) on the Tracker (for shortcuts and effects). Sorry about that !
