### ISSUE TITLE
Problem with right click (to change time sig) and adding patterns to song

### ISSUE THREAD

**Issue by bram2000** [gibbonjoyeux/VCV-Biset#16]
Hiya, thanks for all of your work on the Biset tracker, it looks very promising. I've been playing with it but have run into a few issues.

1) I can't seem to right click on the pattern screen to change the pattern length/time sig (as suggested in the manual)

2) Adding patterns to the timeline doesn't work. I can add and select patterns but adding clicking on the timeline doesn't do anything.

I'm on an M1 Macbook Pro, VCV Rack 2 Pro. Thanks!

**Comment by bram2000** [comment]
<img width="337" alt="Screenshot 2024-01-10 at 21 12 50" src="https://github.com/gibbonjoyeux/VCV-Biset/assets/5268174/b86feb22-ed62-4b9f-a928-0572fb6c5ec3">

If I right click on a pattern I'm missing all of the options about pattern length etc.

**Comment by gibbonjoyeux** [comment]
Hello !
Pattern length, columns, position in timeline, etc. are locked when the Tracker is playing.
While playing, you can only edit the pattern notes and CV lines content.
If you stop the tracker, it should be available again :) Let me know if this fixes the issue

**Comment by bram2000** [comment]
Yes that works, now I feel stupid!

Thanks for the swift response, loving your work.

**Comment by gibbonjoyeux** [comment]
Don't worry !
Thank you very much :)
