### ISSUE TITLE
Why is there No external clock?  Or a remote Start/stop ? 

### ISSUE THREAD

**Issue by JeffGreenlee42** [gibbonjoyeux/VCV-Biset#34]
After playing around with Biset Tracker... I gradually realized... "hey!  Why can't I control this sequencer with an external clock?  Just curious about why this is not a feature?  I was not able to find a menu or input port where the Clock/start/stop or even a reset could be controlled with an external signal?   Are there any plans to include this in future versions?

**Comment by gibbonjoyeux** [comment]
Hello :)
You can use the T-Control module (https://library.vcvrack.com/Biset/Biset-Tracker-Control). It allows you to play / stop the tracker, control it with clock or phase and you can even change playing patterns with triggers :)
