### ISSUE TITLE
Regex inactive startup

### ISSUE THREAD

**Issue by firolightfog** [gibbonjoyeux/VCV-Biset#8]
Currently Regex disables the lines at startup of VCV Rack. I'd suggest to enable it right from the start. 

<img width="403" alt="image" src="https://github.com/gibbonjoyeux/VCV-Biset/assets/34127628/75fcefd0-b1c5-43ea-8cfe-ad437def9602">

**Comment by gibbonjoyeux** [comment]
I think I could add this as an option in the context menu (perhaps even as the default behavior).

As I initially designed it to use it on live coding performance (with sometimes some pre-written expressions), I wanted a module doing nothing on start-up.

But I see more and more people using it more as a "simple" sequencer so your advice is quite appropriate ! I will add this to my TODO list :)

**Comment by gibbonjoyeux** [comment]
Done ! It should be available with the 2.0.8 update with some new features (2.0.7 has already been sent to VCV)
The option will be available with a simple right click :)
